FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# create non-root user
RUN adduser -S komal

# switch to non-root user
USER komal

EXPOSE 3000

CMD ["node", "app.js"]